[build]
  command = "npm run build:prerender"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/ja"
  status = 302
  conditions = { Language = ["ja"] }

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  conditions = { Language = ["en"] }

[[redirects]]
  from = "/"
  to = "/ja"
  status = 302
  conditions = { Country = ["JP"] }

[[redirects]]
  from = "/"
  to = "/ja"
  status = 302

[[redirects]]
  from = "/login"
  to = "/login"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/signup"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/ja"
  status = 302
